#!/bin/zsh

function link () {
# skip files already linked

if [[ -L $2/$1 && $(readlink -f $2/$1) == $(readlink -f $1) ]]
then
    echo "\"$2/$1\" already linked: skipping"
    return 0
fi

# backup any real file
if [[ -f $2/$1 ]]
then
    echo "\"$2/$1\" exists: moving it to \"$2/$1.backup\""
    mv $2/$1 $2/$1.backup
fi

# link to dotfiles
ln -s $(readlink -f $1) $2/$1
echo "Linked: \"$2/$1\" -> \"$1\""
}

link .zshrc ~

mkdir -p ~/.config/nvim
link init.vim ~/.config/nvim

mkdir -p ~/.oh-my-zsh/custom
link notify-osd.zsh ~/.oh-my-zsh/custom

mkdir -p ~/.oh-my-zsh/custom/themes
link bonetti.zsh-theme ~/.oh-my-zsh/custom/themes

mkdir -p ~/.oh-my-zsh/custom/plugins/ag
link ag/_ag            ~/.oh-my-zsh/custom/plugins
link ag/ag.plugin.zsh  ~/.oh-my-zsh/custom/plugins

