#!/bin/sh
cd ~

if [ ! grep -q "neovim-ppa" /etc/apt/sources.list /etc/apt/sources.list.d/* ]; then
    echo "Intalling neovim-ppa"
   sudo add-apt-repository ppa:neovim-ppa/unstable
else
    echo "neovim-ppa already installed: skipping"
fi

sudo apt-get update
sudo apt-get install zsh curl fonts-powerline exuberant-ctags clang-format-3.7 silversearcher-ag build-essential cmake gitk git-gui \
    python-dev python-pip python3-dev python3-pip neovim


if [ ! -d ".oh-my-zsh" ]; then
    echo "Intalling oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
    echo "oh-my-zsh already installed: skipping"
fi

if [ ! -f ".local/share/nvim/site/autoload/plug.vim" ]; then
    echo "Intalling vim-plug"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim




else
    echo "vim-plug already installed: skipping"
fi

git config --global user.email "tiago.bonetti@gmail.com"
git config --global user.name "Tiago Bonetti"

