#!/bin/sh
cd ~
sudo apt-get install zsh curl fonts-powerline exuberant-ctags clang-format-3.5 silversearcher-ag build-essential cmake python-dev python3  gitk

if [ ! -d ".oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
    echo "oh-myzsh already installed: skipping"
fi

if [ ! -d "~/.local/share/nvim/autoload/plug.vim" ]; then
    curl -fLo ~/.local/share/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo "vim-plug already installed: skipping"
fi

git config --global user.email "tiago.bonetti@gmail.com"
git config --global user.name "Tiago Bonetti"

