# All SpaceVim option below [option] section
[options]
    automatic_update = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[layers]]
  name = "default"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "denite"
  
[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp",
    "python",
  ]  

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#python" 

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#markdown"

[[custom_plugins]]
  repo = "peterhoeg/vim-qml"

